# for travis-ci.org
language: android
android:
  components:
    - tools
    - tools  # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - platform-tools
    - build-tools-25.0.1
    - android-24
    - extra-android-m2repository
#    - extra-google-m2repository

jdk: oraclejdk8

script:
  - ./gradlew --stacktrace build

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
#    - $HOME/.gradle/native/
#    - $HOME/.gradle/daemon/native/
